### ISSUE TITLE
Platform updates

### ISSUE THREAD

**Issue by Chalarangelo** [30-seconds/30-seconds-web#147]
### Preface

While Gatsby has been our tool of choice and base of our infrastructure for about a year now, we have faced several difficulties with it over the months which have made working with it in the future somewhat of an issue. Namely, we have trouble updating to newer versions, keeping up with changes and it doesn't support some of the sort of weird cases 30 seconds needs to be supported. 

For that reason, we will be steadily moving towards a new internal platform, one we can fully control and build as we want. This might be in the form of a less opinionated and/or more configurable tool, a very different setup for Gatsby itself or a custom solution built from the ground up. The first step was to build what we call `yild`, introduced in #135 and replacing parts of the Gatsby API in the project. 

As `yild` will steadily grow into a tool to suit our needs, here are the requirements for the finished tooling, as well as some research, proposed solutions etc.

**Comment by Chalarangelo** [comment]
### Requirements

This aims to be a cohesive list of requirements to help us move forward with the next steps of this project. 

#### From Gatsby
- [ ] **Blazing fast** - While Gatsby's nuances might prevent some of our pages from reaching performance score of 100, it is quite fast. We definitely need to be up to par with it regardless of solution.
- [ ] **Code splitting, chunks etc.** - Gatsby handles a lot of the dirty work behind the scenes, we should understand what it is that it does and we need, so that we can better work towards an implementation that covers the same needs.
- [ ] **Helmet, metadata, SEO** - Helmet is quite cool and can save us time in development, regardless of solution. Let's try to support it, so that we can use existing logic in the future.
- [ ] **Dynamic route generation** - We depend on this kind of functionality quite heavily. It is imperative that we set up the next toolchain to use this and work with existing code (providing sort of polyfills for `createPage` for example) to generate all pages as necessary.
- [ ] **Sitemaps** - This is currently supported via plugin. As our codebase logic is quite advanced already, we could theoretically decouple from the plugin quite early on and be done with the requirement.
- [ ] **Hot reloading components** - Developer experience is paramount, this will ensure that it stays as-is at the very least.
- [ ] **Service workers, offline app, manifest** - PWA functionality and precached resources are very important, we need to implement this or use a tool that does our work for us. Additionally, we could expand on the behavior of this to make the website even better offline and/or give it more of an app feeling.
- [ ] **Netlify headers** - Supported via plugin, we could take a look under the hood and figure out more specific details about this.
- [ ] **Redirects etc** - Probably very little effort is needed here, just check everything thoroughly to ensure consistency.
- [ ] **404 handling** - We should take a look at what Gatsby does and figure out what we need to do to keep the behavior close to what we currently have.
- [ ] **GraphQL layer, data-view decoupling** - Gatsby uses `page-data.json` files to pass data to each page and minimize content loads. We should do something very similar which will also allow us to handle a few other things such as no-reload navigation.
- [ ] **Preload, prefetch etc.** - Preloading resources is probably a very good strategy and Gatsby uses it. We should figure out how to handle this on our own and optimize pages even further.
- [ ] **Navigating without reloading** - Internal navigation should not require reloading. New page content should be fetched and parsed into the page without reloading at all.
- [ ] **Handling external/internal links dynamically** - Supported via plugin. We could take a look under the hood and get rid of the plugin sooner or later.

#### New features
- [ ] **SSR, pre-rendered HTML content, hydration (partial?)** - Not entirely sure how Gatsby handles SSR and hydration, but we should SSR pages and then hydrate them on the client. This will provide performance and SEO benefits, as well as allow us to partially hydrate pages if possible (e.g. footer might not require hydration).
- [ ] **Hot reloading data** - Hot reloading data in development mode is not currently available, except for a `yild` hack I coded a while back. If at all possible, we need to support this and it might be actionable immediately, helping us narrow down other requirement options.
- [ ] **Dev-only routes and developer-specific views** - Partially implemented as dev-specific views via `yild` hacks, we should try to provide a better developer experience via customized CMS-like interfaces.
- [ ] **CSS splitting when possible/necessary** - We can inline some critical CSS and not load all CSS on every page (e.g. snippet page bundle is not necessary in listing pages, as it goes unused). 

#### Nice to haves
- [ ] **Animated navigation, quick swap, modal snippets** - We could add a loading animation when moving from one page to another without reloading. That way we provide some feedback for the user and make UX a bit more lively.

**Comment by Chalarangelo** [comment]
### Research

As we are moving forward, it's best to document research steps one by one to ensure we don't go around chasing our tails during this process. Here are some initial ideas and options:

#### Full-fledged solutions

- [Gatsby](https://www.gatsbyjs.com/) is the current solution we use and, while reasonably satisfying, we are trying to change our build tooling to something more in line with our needs.
- [React Static](https://github.com/react-static/react-static) is an alternative to Gatsby and seems to deliver on a lot of levels. Migration from one to the other might not be very difficult and we could get a prototype set up to check if it suits any of our needs.
- I have not really looked into [Next.js](https://nextjs.org/) all that much, but it might be a worthwhile candidate yet. We can take a quick look and compare it to the rest of the solutions we are currently considering.
- [Create React App](https://create-react-app.dev/) is a tried and tested solution, but we would most likely require to `eject` from it to support everything we need.

#### Partial solutions, ideas, tools, articles

- React supports SSR via [ReactDOMServer](https://reactjs.org/docs/react-dom-server.html), which we could use if we are to build a custom solution ourselves.
- [React Router](https://reactrouter.com/web/guides/server-rendering) is a very popular solution and v6 (in beta at the time of writing) will be a merger between that and `@reach/router` which is used by Gatsby and other toolchains. Let's keep an eye out.
- Here are two pretty comprehensive articles on SSR ([part 1](https://medium.com/bucharestjs/upgrading-a-create-react-app-project-to-a-ssr-code-splitting-setup-9da57df2040a) and [part 2](https://medium.com/bucharestjs/adding-state-management-with-redux-in-a-cra-srr-project-9798d74dbb3b)) by Andrei Duca, who seems to have figured out a way to use SSR with `create-react-app` without ejecting.
- [`react-dev-utils`](https://www.npmjs.com/package/react-dev-utils) might come in handy and seem to be used by pretty much everyone for a few different things. Let's keep them in mind.
- The [watch](https://www.npmjs.com/package/watch) npm package seems like a promising solution to rebuilding content if we can't find anything better.

**Comment by Chalarangelo** [comment]
### Build process outline [WIP]

To have a coherent plan moving forward, we can outline the build process in broad strokes:

#### Preprocessing

- Fetch content from repos
- Build assets, icons, fonts, backgrounds
- Extract snippets
- Setup environment and cache

#### Build

- SSR pages, prepare for hydration on the client
- Prepare JSON files for serving
- Setup any hosting-related files
- Copy assets, fonts etc.
- Generate bundles, compile CSS

**Comment by Chalarangelo** [comment]
### GraphQL layer, data-view decoupling [WIP]

This might be one of the greatest challenges yet, so we will tackle this first on its own. Here's a quick rundown of planned changes in `yild@v2` or so:

- Process each snippet, generating partial data into `/repoName/s/snippetName/snippet.json`. This file will contain all extracted snippet data. Recommendations, breadcrumbs, SEO and metadata not included.
- Process snippet recommendations after generating the list of snippets, generate partial data into `/repoName/s/snippetName/recommendedSnippets.json`.
- Process snippet metadata (rest) and generate `/repoName/s/snippetName/meta.json`.
- Process listing pages, generating partial data into `/repoName/listSortPath/listPageNumber/snippetList.json`. This file will contain extracted data for just the snippet list.
- Process listing data for the rest of the properties and metadata (rest), generate `/repoName/listSortPath/listPageNumber/meta.json`

**Comment by Chalarangelo** [comment]
For the time being, we are going to work on general-purpose changes, such as generating sitemaps and page data ourselves, as well as handling developer experience with the current setup. If/when we are ready, we will take another look at Gatsby and decide on our next steps. Bear in mind that, if updating becomes possible again at some point, we will probably stick with Gatsby for a while longer, as we are in no rush to migrate to an entirely new toolchain.

**Comment by Chalarangelo** [comment]
#150 will be released sometime this month. We are tackling:

- **GraphQL layer, data-view decoupling** - We are providing our own solution, which we'll tie into Gatsby for the time being
- **Sitemaps** (#148) - We are generating customized sitemaps in order to get rid of the existing plugin
- **Dynamic route generation** - We are tackling this by moving route generation logic and data one step back, so that any toolchain can theoretically hook into the existing JSON data.
- **Hot reloading data** - If possible we will experiment with `createPagesStatefully` and `chokidar` to refresh data in development mode.
- **Dev-only routes and developer-specific views** - We will take a look at the `onCreateDevServer` Gatsby lifecycle hook, might allow us to do some interesting things and also utilize existing infrastructure without the need to code a server API from scratch.

**Comment by Chalarangelo** [comment]
The aforementioned changes about **dev-only routes**, **hot reloading data** and **developer-specific-views** will be released next week or so in order to test the changes one step at a time. The plan is to use `createPagesStatefully` in combination with `chokidar` and `onCreateDevServer` to create a simple hot reloading system along with a POST route to create a new snippet per repository. This is obviously a very early stage of testing for this, so any changes may be refactored in the future.

**Comment by Chalarangelo** [comment]
Bumped Gatsby in #164. As we can now bump this dependency to get any changes made to it, we can stay on this platform for as long as we want, unless we end up with some other issue. Let's keep working on the rest of the points mentioned and see where we land.

**Comment by Chalarangelo** [comment]
#167 will be introduced a real hot reload mode and dev-only routes, allowing for content creation and editing via a VSCode bridge. This might be the first step towards a true CMS-like experience and probably the hardest one.

**Comment by Chalarangelo** [comment]
### Update (Sep 13, 2020)

After research, development and testing, we have decided to stick with Gatsby for a while longer. The features we want can be built and supported by the current infrastructure and the Gatsby team seems to be working hard on performance issues that were introduced due to the latest Lighthouse metrics. We can keep the `yild` implementation mostly separate from Gatsby, injecting code via Node APIs as necessary and use this pattern to be ready for any changes we might decide to make at a later time. This still means some housekeeping and maintenace, as well as some new features landing on our platform sooner or later, but definitely faster development as we are not facing a full-scale migration effort right now. 

I'll update notes accordingly.

**Comment by Chalarangelo** [comment]
### Leftover tasks roadmap

- **Service workers, offline app, manifest** - Plugin investigation underway
- **Netlify headers** - Plugin investigation underway
- **Preload, prefetch etc.** - Investigation underway
- **Handling external/internal links dynamically** - Plugin investigation underway
- **CSS splitting when possible/necessary** - While little to no effort is required to make changes here, this is unnecessary as our CSS load is quite small. Closing for now.
- **Animated navigation, quick swap, modal snippets** - As this is wishlisted right now, we are not going to tackle it anytime soon, unless we complete everything else first.

**Comment by Chalarangelo** [comment]
#173 bumps any plugins that might be of interest, will close this issue with its release.
