### ISSUE TITLE
Development server endpoints and pages

### ISSUE THREAD

**Issue by Chalarangelo** [30-seconds/30-seconds-web#246]
- [ ] Promotional card page (editable/contenteditable) #239  - with image export
- [x] Page creation endpoint - TODO: Revamp
- [ ] Config editor - Twitter bot available snippets, content configs, collection configs
- [ ] Image uploader #180 
- [ ] Image gallery for selecting images - requires the previous 2
- [ ] Commit endpoint - Allow post scheduling, author fields, pushing etc. #260

**Comment by Chalarangelo** [comment]
Closing the issue as it is has gone stale. A brief catchup on what has transpired since its opening:
- Promotional content is generally handcrafted so there's no need for an endpoint at this time.
- Page creation has been simplified with internal utilities, not applicable at this time.
- Configurations are in their own repo and easy to tweak.
- Image upload will be bundled along with other changes to create an easier way to add images.
- Image gallery might be worth creating in a future version, but it's not a priority.
- Commit endpoint is not necessary, scheduling has been added and other issues are being worked on.
