### ISSUE TITLE
Rebranding (2021)

### ISSUE THREAD

**Issue by Chalarangelo** [30-seconds/30-seconds-web#343]
After months in the making, it's time for the official rebranding of the project, organization and everything in-between. The plan is to roll out all of these changes as one big bundle, updating social profiles and everything on GitHub and the website all at the same time.

This issue serves as a roadmap and a checklist of changes to be made.

**Comment by Chalarangelo** [comment]
- [ ] Design new logo and GitHub imagery
- [ ] Update website
- [ ] Update palettes etc.
- [ ] Remove outdated repos (#339)
- [ ] Investigate UI changes for new branding (#331, #330, #337, #340)
- [ ] Update About
- [ ] Evaluate data collection tools [1][2]
- [ ] Update GitHub
- [ ] Update bot (GitHub and email avatars)
- [ ] Update LinkedIn
- [ ] Update Twitter, check post frequency (again)
- [ ] Decide about Facebook - Probably terminate
- [ ] Update ProductHunt
- [ ] Update Dev.To and prepare a blog about the rebranding
- [ ] Deprecate expertise titles on the website, as they are confusing (indicators might remain - needs investigation)

- [1] Hotjar might not be necessary anymore, as we are not running too many surveys at the moment and might make it harder for people to accept cookies etc. In keeping with deciding on a consistent brand, such tools should be evaluated and we should stick to a set of tools we think suit our needs in the long term. 
- [2] The new Analytics could be an option if we can figure out how to use them.

**Comment by Chalarangelo** [comment]
If all goes according to plan, the rebranding will go live this weekend.
