### ISSUE TITLE
Create a design system

### ISSUE THREAD

**Issue by Chalarangelo** [30-seconds/30-seconds-web#370]
Our current designs and implementation are pretty well-organized, however we lack a proper design system with guidelines etc. We should aim to create the following:

- [ ] Shared Figma library - This will include palettes, shadows, font styles and any components that will help us prototype fast
- [ ] Design guidelines wiki - Any guidelines we can gather, design language etc.
- [x] Copy guidelines wiki - Guidelines on how to create copy and present a consistent image.
- [ ] Design examples wiki - A shared document of how everything fits together
- [x] Mockups and reusable resources - A first step towards a brand book
- [x] Logo files - All versions of our logo and splash imagery for quick access

Note that some of the above can either live in a wiki here or we can create a dedicated repository for all of the design/branding/media work and add everything there.

**Comment by Chalarangelo** [comment]
Closing, as we're tracking this internally at this time.
